blog/urls.py
from django.conf.urls import url, include

from .views import *


urlpatterns = [
    url(r'^$', view=blog_homepage,name='blog_homepage'),
    url(r'^(?P<slug>[-\w]+)/$', view=blog_category,name='blog_category'),
    url(r'^create/$', view=create_post,name='blog_create'),
    url(r'^edit/(?P<slug>[-\w]+)/$', view=edit_post,name='blog_edit'),
    url(r'^detail/(?P<slug>[-\w]+)/$', view=blog_details, name='blog_detail'),




    ]

vavouras/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.conf.urls.static import static
from homepage.views import *
from django.conf import settings
from django.contrib.sitemaps.views import sitemap
from site_map.views import *
from django.views.generic import TemplateView


sitemaps = {
    'art':ArtSitemap,
    'project':ProjectSitemap,
}

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', Homepage.as_view(), name='home'),
    url(r'^about/$', AboutPage.as_view(), name='about'),
    url(r'^art/$', ArtPage.as_view(), name='art'),
    url(r'^art/(?P<slug>[-\w]+)/$', view=choosed_art, name='choosed_art'),
    url(r'^projects/$', ProjectsPage.as_view(), name='projects'),
    url(r'^project/(?P<slug>[-\w]+)/$', view=project, name='project'),
    url(r'^project/image/(?P<dk>\d+)/$', view=project_image, name='project_image'),
    url(r'^project-about/(?P<slug>[-\w]+)/$', view=project_about, name='project_about'),
    url(r'^message$', view=message_success, name='message'),
    url(r'^sitemap\.xml',sitemap, {'sitemaps': sitemaps}),
    url(r'^robots.txt$', TemplateView.as_view(template_name="it_worker/robots.txt", content_type="text/plain"), name="robots_file")

]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

homepage/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils.safestring import mark_safe

# Create your models here.

def upload_photo(instance,filename ):
    return 'homepage/{0}/{1}'.format(instance.title, filename)

class Welcome_page(models.Model):
    active = models.BooleanField(default=True)
    title = models.CharField(unique=True, max_length=100, )
    logo = models.ImageField(upload_to=upload_photo)
    second_banner = models.ImageField(upload_to=upload_photo, null= True, help_text='')
    my_skills_section_message = models.CharField(max_length=160,
                                                 default='Would you like to know more or just discuss something?',
                                                 help_text='NO HTML here.')
    #personal_photo = models.ImageField(upload_to='personal_photo/')
    projects_section_message = models.CharField(max_length=160,
                                                 default='My works so far',
                                                 help_text='NO HTML here.')
    art_section_message = models.CharField(max_length=160,
                                                 default='See my demo sites and the future apps.',
                                                 help_text='NO HTML here.')
    blog_section_message = models.CharField(max_length=160,
                                                 default="See our latest posts in <a href='www.vavourasblog.com!'>www.vavourasblog.com!</a>",
                                                 help_text='USE HTML here.')
    seo_title = models.CharField(max_length=60, null=True, blank=True, help_text='Dont change it!')
    seo_keywords = models.CharField(max_length=160, null= True, blank=True, help_text='Use words that appears oon text, synonyms and no spam for better use.')
    seo_description = models.CharField(max_length=160, null= True, blank=True, help_text='The text thats appears on google for the site description.')

    about_me = models.CharField(max_length=20, default='ABOUT ME')
    about_me_image = models.ImageField(upload_to=upload_photo, null=True)
    personal_photo = models.ImageField(upload_to=upload_photo, null=True)

    my_skills = models.CharField(max_length=20, default='MY SKILLS')
    project = models.CharField(max_length=20, default='Projects')

    left_text = models.TextField(default='Left part')
    center_text = models.TextField(default='Center part')
    right_text = models.TextField(default='Right part')

    #css
    body_background_color = models.CharField(max_length=10, default='', verbose_name='Background Color of all page' )
    menu_hover_color = models.CharField(max_length=10, default='', verbose_name='Menu hover color')
    skills_color_primary = models.CharField(max_length=10, default='#13836c' , verbose_name='Service Primary color', help_text='Change the color on service section')
    skills_color_secondary = models.CharField(max_length=10, default='#45b59e', verbose_name='Service Secondary  Color')

    main_color_fonts = models.CharField(max_length=10, default='#f4d9d9')
    secondary_color_font = models.CharField(max_length=10, default='#f4d9d9', verbose_name='Menu color and paragraphs etc')
    third_color_font = models.CharField(max_length=10, default='#f4d9d9', null=True, blank=True, help_text='You control here the titles of projects and the urls.', verbose_name='Ahref color controller')

    class Meta:
        verbose_name_plural = '1.Anything about index page'

    def __str__(self):
        return self.title

    def logo_tag(self):
        return mark_safe('<img src="https://s3.eu-west-2.amazonaws.com/levavour/media/%s" width="100px" height="100px" />'%(self.logo))
    logo_tag.short_description = 'Logo Image'

    def second_banner_tag(self):
        return mark_safe('<img src="https://s3.eu-west-2.amazonaws.com/levavour/media/%s" width="150px" height="150px" />'%(self.second_banner))
    second_banner_tag.short_description = 'Second banner Image'

    def about_me_image_tag(self):
        return mark_safe('<img src="https://s3.eu-west-2.amazonaws.com/levavour/media/%s" width="100px" height="100px" />'%(self.about_me_image))
    about_me_image_tag.short_description = 'About me'

    def personal_photo_tag(self):
        return mark_safe('<img src="https://s3.eu-west-2.amazonaws.com/levavour/media/%s" width="100px" height="100px" />'%(self.personal_photo))
    personal_photo_tag.short_description = 'Personal_photo'

class MainBanner(models.Model):
    active = models.BooleanField(default=True)
    title = models.CharField(max_length=100)
    alt = models.CharField(max_length=100)
    image = models.ImageField(upload_to='banner/')
    header_message = models.CharField(max_length=100, default='George Avdoulos', help_text='Banner header message')
    text_message = models.TextField(help_text='Banner text message', default='Le Vavour Illustrator - Designer')
    color_text = models.CharField(max_length=10, default='#ffffff')
    font = models.CharField(max_length=200, default='http://fonts.googleapis.com/css?family=Roboto+Slab:400,700,100%7CRoboto:400,700,300,100')
    class Meta:
        verbose_name_plural = '2. Control the main banner'

    def __str__(self):
        return self.title

    def image_tag(self):
        return mark_safe('<img src="https://s3.eu-west-2.amazonaws.com/levavour/media/%s" width="300px" height="250px" />'%(self.image))
    image_tag.short_description = 'Image'
    def image_tag_tiny(self):
        return mark_safe('<img src="https://s3.eu-west-2.amazonaws.com/levavour/media/%s" width="150px" height="100px" />'%(self.image))
    image_tag.short_description = 'Image'

class AboutMe(models.Model):
    title = models.CharField(max_length=50, default='default')
    text = models.TextField(blank=True, help_text='Use HTML if you want!')
    class Meta:
        verbose_name_plural = '3. About Section'

    def __str__(self):
        return self.title


class AboutMeBar(models.Model):
    title = models.CharField(max_length=100,)
    percent = models.IntegerField(default=50, verbose_name='Number')
    icon = models.CharField(max_length=100,
                            null=True,
                            help_text='Here you use bootstrap icons, you can find them here. http://bootstrapmaster.com/live/one/icons_set2.html')
    class Meta:
        verbose_name_plural = 'The stats on front_page'
    def __str__(self):
        return self.title

class Services(models.Model):
    icon = models.CharField(max_length=100, null=True, help_text='Here you use bootstrap icons, you can find them here. http://bootstrapmaster.com/live/one/icons_set2.html')
    title = models.CharField(max_length=100)
    text = models.TextField(max_length=400, help_text='If you frontpage problems use <br> on end of line')
    order = models.IntegerField(default=1, help_text='Set the order if you want.')
    active = models.BooleanField(default=True)
    class Meta:
        ordering = ['order']
        verbose_name_plural = '4. Skill Set on front pages'
    def __str__(self):
        return self.title

class Contact(models.Model):
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    email = models.EmailField()
    phone = models.CharField(max_length=10)
    message = models.TextField()
    day_added = models.DateField(auto_now=True)
    is_readed = models.BooleanField(default=False)

    def __str__(self):
        return self.last_name

    def fullname(self):
        return '%s %s'%(self.first_name, self.last_name)

projects/forms.py
from django.forms import formset_factory
from .models import *

ImageFormSet = formset_factory(ImageProject, extra=5)

homepage/views.py
from django.shortcuts import render
from django.shortcuts import render, render_to_response, HttpResponseRedirect, HttpResponse,\
    redirect, get_object_or_404
from django.contrib import messages
from django.core.mail import send_mail
from django.views.generic import ListView, FormView, TemplateView
from .models import *
from .tools import projects_filters
from blog.models import Post, PostCategory
from art.models import Art, ImageArt
from projects.models import Projects, ImageProject, SkillProgress, ProjectCategory
from blog.views import *
from contact.forms import *
import datetime
# Create your views here.

'''
def get_user_ip(request):
    x_forwarded_for = request.META.get('HTTP_X_FORWARDED_FOR')
    if x_forwarded_for:
        print("returning FORWARDED_FOR")
        ip = x_forwarded_for.split(',')[-1].strip()
    elif request.META.get('HTTP_X_REAL_IP'):
        print("returning REAL_IP")
        ip = request.META.get('HTTP_X_REAL_IP')
    else:
        print("returning REMOTE_ADDR")
        ip = request.META.get('REMOTE_ADDR')


def language(request):
    lang = 'gr'
    response = HttpResponseRedirect('/')
    response.set_cookie('lang', lang)
    return response
'''


def initial_data(request):
    welcome_page = Welcome_page.objects.filter(active=True).last()
    banner = MainBanner.objects.filter(active=True).last()
    about = AboutMe.objects.get(id=1)
    arts = Art.my_query.active()
    return [welcome_page, banner, about]


class Homepage(FormView):
    template_name = 'it_worker/index.html'
    form_class = ContactForm
    success_url = ''

    def get_context_data(self, **kwargs):
        context = super(Homepage, self).get_context_data(**kwargs)
        welcome_page, banner, about = initial_data(self.request)
        arts, projects = Art.my_query.active()[0:3], Projects.my_query.active()[0:3]
        context.update(locals())
        return context

    def form_valid(self, form):
        if form.is_valid():
            form.save()
            send_mail('New Contact', '%s'%(form.cleaned_data.get('message')),
                      recipient_list=['lirageika@hotmail.gr'],
                      fail_silently=True,
                      from_email='%s' %(form.cleaned_data.get('email')))
            messages.success(self.request, 'I will contact you shortly!')
            return redirect('/')


class AboutPage(TemplateView):
    template_name = 'it_worker/about_page.html'

    def get_context_data(self, **kwargs):
        context = super(AboutPage, self).get_context_data(**kwargs)
        welcome_page, banner, about = initial_data(self.request)
        context.update(locals())
        return context


def message_success(request):
    return render(request, 'it_worker/message.html')





class ProjectsPage(ListView):
    model = Projects
    template_name = 'it_worker/projects.html'

    def get_queryset(self):
        queryset = Projects.objects.all()
        search_name, cate_name, queryset = projects_filters(self.request, queryset)
        return queryset

    def get_context_data(self, **kwargs):
        context = super(ProjectsPage, self).get_context_data(**kwargs)
        welcome_page = Welcome_page.objects.last()
        categories = ProjectCategory.objects.all()
        search_name, cate_name, queryset = projects_filters(self.request, self.object_list)
        context.update(locals())
        return context


def project(request, slug):
    welcome_page = Welcome_page.objects.filter(active=True).last()
    project = get_object_or_404(Projects, slug=slug)
    images = ImageProject.my_query.post_related_and_active(post=project)
    context = locals()
    return render_to_response('creative/index.html', context)


class ArtPage(ListView):
    model = Art
    template_name = 'it_worker/art_page.html'

    def get_queryset(self):
        queryset = Art.objects.all()
        return queryset

    def get_context_data(self, **kwargs):
        context = super(ArtPage, self).get_context_data(**kwargs)
        welcome_page = Welcome_page.objects.all().last()
        context.update(locals())
        return context


def choosed_art(request, slug):
    welcome_page = Welcome_page.objects.filter(active=True).last()
    project = get_object_or_404(Art, slug=slug)
    images = ImageArt.my_query.post_related_and_active(post=project)
    context = locals()
    return render_to_response('it_worker/art_details.html', context)


def project_image(request,dk):
    welcome_page = Welcome_page.objects.filter(active=True).last()
    image = get_object_or_404(ImageProject, id=dk)
    project = image.project_related
    context = locals()
    return render_to_response('creative/detail.html', context)


def project_about(request, slug):
    project = get_object_or_404(Projects, slug=slug)
    welcome_page = Welcome_page.objects.filter(active=True).last()
    skill_bar = SkillProgress.objects.filter(project_related = project)
    context = locals()
    return render_to_response('creative/about.html', context)

projects/views.py
from django.shortcuts import render

# Create your views here.

homepage/templates/it_worker/about_page.html
{% extends 'it_worker/index.html' %} {% load static %}
{% block static %}
    <style>
        .text-parallax.parallax-image1 {
            background: url('{% static 'my_images/project.jpg' %}') center center no-repeat fixed;
            -webkit-background-size: cover;
            -moz-background-size: cover;
            -o-background-size: cover;
            background-size: cover;
            height: 70%;
        }

    #intro .item {
          height: 100%;
          background: url('{% static 'my_images/project.jpg' %}') center center no-repeat;
          -webkit-background-size: cover;
          -moz-background-size: cover;
          -o-background-size: cover;
          background-size: cover;
          -webkit-backface-visibility: hidden;
        }
    </style>
    <style>
        .text {
           width: 100%;
           text-align: center;
           margin-top: 20px;
           height: 70px;
        }
        .area {
           width: 100%;
           float: left;
           margin-top: 15px;
        }

        .area .input,
        .area .input label {
           width: 100%;
           float: left;
           position: relative;
        }

        .area .input {
           overflow: hidden;
           border-radius: 2px;
           color: #fff;
            background-color: #555555;
           box-shadow:0 2px 5px 0 rgba(0, 0, 0, 0.16), 0 2px 10px 0 rgba(0, 0, 0, 0.12);
           transition: 300ms;
           -webkit-transition: 300ms;
           -ms-transition: 300ms;
        }

        .area .input input {
           display: none;
        }

        .area .input label {
           font-weight: 400;
           color: #fff;
           text-align: center;
           text-transform:uppercase;
           cursor: pointer;
           font-size: 14px;
           z-index: 3;
           transition: 300ms;
           -webkit-transition: 300ms;
           -ms-transition: 300ms;
           height: 45px;
           line-height: 45px;
        }

.area .input:hover{
   box-shadow:0 5px 11px 0 rgba(0, 0, 0, 0.18), 0 4px 15px 0 rgba(0, 0, 0, 0.15)
}
.area .input label:hover {
   letter-spacing: .8px;

}

.click-efect {
   position: absolute;
   top: 0;
   left: 0;
   background: rgba(0, 0, 0, 0.2);
   border-radius: 50%;
}


.col-3 {
   width: 25%;
   float: left;
   padding: 0 15px;
}

.row {
   margin: 0 -15px;
}

*,
*:after,
*::before {
   -webkit-box-sizing: border-box;
   -moz-box-sizing: border-box;
   box-sizing: border-box;
   margin: 0;
   padding: 0;
   text-decoration: none;
}


    </style>
    <script>
    $(".area .input").click(function(e) {

   $("label[type='checkbox']", this);
   var pX = e.pageX,
      pY = e.pageY,
      oX = parseInt($(this).offset().left),
      oY = parseInt($(this).offset().top);

   $(this).addClass('active');

   if ($(this).hasClass('active')) {
      $(this).removeClass('active');
      if ($(this).hasClass('active-2')) {
         if ($("input", this).attr("type") == "checkbox") {
            if ($("span", this).hasClass('click-efect')) {
               $(".click-efect").css({
                  "margin-left": (pX - oX) + "px",
                  "margin-top": (pY - oY) + "px"
               });
               $(".click-efect", this).animate({
                  "width": "0",
                  "height": "0",
                  "top": "0",
                  "left": "0"
               }, 400, function() {
                  $(this).remove();
               });
            } else {
               $(this).append('<span class="click-efect x-' + oX + ' y-' + oY + '" style="margin-left:' + (pX - oX) + 'px;margin-top:' + (pY - oY) + 'px;"></span>')
               $('.x-' + oX + '.y-' + oY + '').animate({
                  "width": "500px",
                  "height": "500px",
                  "top": "-250px",
                  "left": "-250px"
               }, 600);
            }
         }

         if ($("input", this).attr("type") == "radio") {

            $(".area .input input[type='radio']").parent().removeClass('active-radio').addClass('no-active-radio');
            $(this).addClass('active-radio').removeClass('no-active-radio');

            $(".area .input.no-active-radio").each(function() {
               $(".click-efect", this).animate({
                  "width": "0",
                  "height": "0",
                  "top": "0",
                  "left": "0"
               }, 400, function() {
                  $(this).remove();
               });
            });

            if (!$("span", this).hasClass('click-efect')) {
               $(this).append('<span class="click-efect x-' + oX + ' y-' + oY + '" style="margin-left:' + (pX - oX) + 'px;margin-top:' + (pY - oY) + 'px;"></span>')
               $('.x-' + oX + '.y-' + oY + '').animate({
                  "width": "500px",
                  "height": "500px",
                  "top": "-250px",
                  "left": "-250px"
               }, 600);
            }

         }
      }
      if ($(this).hasClass('active-2')) {
         $(this).removeClass('active-2')
      } else {
         $(this).addClass('active-2');
      }
   }

});
    </script>
{% endblock %}
{% block content %}
    <!-- *** INTRO IMAGE ***
_________________________________________________________ -->
        <div id="intro" class="clearfix">
            <div class="item">
                <div class="container">
                    <div class="row">
                        <div  class="carousel-caption">
                            <h1 style="color: {{ banner.color_text }}" data-animate="fadeInDown">{{ banner.header_message }}</h1>
                            <h2 style="color: {{ banner.color_text }}" data-animate="slideInUp">{{ banner.text_message|safe }}</h2>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <!-- *** INTRO IMAGE END *** -->

                <!-- *** ABOUT ***
        _________________________________________________________ -->
        <div class="section" id="about">
            <div class="container">
                <div class="row">
                    <div class="col-sm-12">
                        <h2 class="title" data-animate="fadeInDown">{{ welcome_page.about_me }}</h2>
                    </div>
                    <div class="col-sm-12">
                        <div class="row">
                            <div style="color:{{ welcome_page.secondary_color_font }}" class="col-sm-6 text-left" data-animate="fadeInUp">
                                {{ about.text|safe }}
                                {% if messages %}
                                <ul>
                                    {% for message in messages %}
                                        <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
                                    {% endfor %}
                                </ul>
                            {% endif %}
                            </div>
                            <div class="col-sm-6" data-animate="fadeInUp">
                                <img src="{{ welcome_page.about_me_image.url }}" class="image img-responsive" alt="{{ welcome_page.title }}">
                            </div>
                        </div>
                    </div>
                    <div class="col-sm-6 col-sm-offset-3 col-md-4 col-md-offset-4 mt-big" data-animate="bounceIn">
                        <img src="{{ welcome_page.personal_photo.url }}" class="image img-circle img-responsive" alt="{{ welcome_page.title }}">
                    </div>
                    <div class="col-sm-12">
                        <div class="row">
                            <div style="color:{{ welcome_page.secondary_color_font }}"  data-animate="fadeInUp">
                                Sleep Twitch is a one man Studio by George Avdoulos , focusing on creative and visual development for different experience projects.

​

     Besides a freelance outsource of Art, Game Design, Level Design and Narrative, The studio is currently focused in the development of its very own 2D platform puzzle adventure Yoric : The Night of Nights
                            </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- /#about -->

        <div class="clearfix"></div>
        <div class="row">
            <div class="container">
                
            </div>
        </div>
        </div>
        <div class="dark-mask"></div>
        <!-- *** CONTACT ***
_________________________________________________________ -->

<div class="section contact" id="contact" data-animate="bounceIn">
    <div class="container">
        <div class="col-md-12">
            {% if messages %}
                {% for message in messages %}
                    <div class="alert alert-success">
                        <strong>Success!</strong> {{ message }}
                    </div>
                {% endfor %}
            {% endif %}

            <h2 class="title">Contact me</h2>
            <div class="row">
                <div class="col-md-8 col-md-offset-2">
                    <form  method="post">{% csrf_token %}
                        <div class="messages">
                            {% if messages %}
                                <ul class="messages">
                                    {% for message in messages %}
                                        <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
                                    {% endfor %}
                                </ul>
                            {% endif %}
                        </div>
                        <div class="controls">
                            <div class="row">
                                <div class="col-md-6">
                                    <input type="text" id="id_first_name" name="first_name" class="form-control" placeholder="Your firstname *" required="required">
                                </div>
                                <div class="col-md-6">
                                    <input type="text" id="id_last_name" name="last_name" class="form-control" placeholder="Your lastname *" required="required">
                                </div>
                                <div class="col-md-6">
                                    <input type="email" id="id_email" name="email" class="form-control" placeholder="Your email *" required="required">
                                </div>
                                <div class="col-md-6">
                                    <input type="number" id="id_phone" name="phone" class="form-control" placeholder="Your phone">
                                </div>
                                <div class="col-md-12">
                                    <textarea id="id_message" name="message" class="form-control" placeholder="Message for me *" rows="4" required="required"></textarea>
                                </div>
                                <div class="col-md-12 text-center">
                                    <input id='my_button' type="submit" class="btn btn-primary btn-lg" value="Send message">
                                </div>
                            </div>
                        </div>
                    </form>
                </div>

            </div>

        </div>
        <!-- /.12 -->
    </div>
    <!-- /.container -->
</div>
<!-- /.section -->

<!-- *** CONTACT END *** -->
<div class="section text-parallax parallax-image1" id="services">
    <!-- /.container -->
    <div class="dark-mask"></div>
</div>

{% endblock %}

homepage/templates/it_worker/include_css.html
{% load static %}
<link href='http://fonts.googleapis.com/css?family=Roboto+Slab:400,700,100%7CRoboto:400,700,300,100' rel='stylesheet' type='text/css'>
    <!-- Bootstrap and Font Awesome css -->
    <link href="{% static 'it_worker/css/font-awesome.css' %}" rel="stylesheet">
    <link href="{% static 'it_worker/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Theme stylesheet -->
    <link href="{% static 'it_worker/css/style.default.css' %}" rel="stylesheet" id="theme-stylesheet">

    <!-- Custom stylesheet - for your changes -->
    <link href="{% static 'it_worker/css/custom.css' %}" rel="stylesheet">

    <!-- owl carousel css -->

    <link href="{% static 'it_worker/css/owl.carousel.css' %}" rel="stylesheet">
    <link href="{% static 'it_worker/css/owl.theme.css' %}" rel="stylesheet">

    <!-- CSS Animations -->
    <link href="{% static 'it_worker/css/animate.css' %}" rel="stylesheet">

    <!-- Favicon -->

    <link rel="shortcut icon" href="{{ welcome_page.logo.url }}">

homepage/templates/it_worker/include_js.html
{% load static %}
<script src="{% static 'it_worker/js/modernizr-2.6.2.min.js' %}"></script>

    <!-- Responsivity for older IE -->
    <!--[if lt IE 9]>
    <script src="{% static 'it_worker/js/respond.min.js' %}"></script>


    <link rel="stylesheet" href="{% static 'portfolio/assets/style.css' %}">
    <!-- animate.css -->
    <link rel="stylesheet" href="{% static 'portfolio/assets/animate/animate.css' %}" />
    <link rel="stylesheet" href="{% static 'portfolio/assets/animate/set.css' %}" />

    <!-- gallery -->
    <link rel="stylesheet" href="{% static 'portfolio/assets/gallery/blueimp-gallery.min.css' %}">

homepage/templates/it_worker/message.html
{% extends 'it_worker/index.html' %}



{% block content %}
    <div style="margin-top: 15%">
    {% if messages %}
<ul class="messages">
    {% for message in messages %}
    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
    {% endfor %}
</ul>
{% endif %}
    <p>Thank you</p>
    </div>
{% endblock %}

homepage/templates/it_worker/navbar.html
{% load static %}

   <!-- *** NAVBAR ***
_________________________________________________________ -->

    {% block upper_bar %}
    <div class="navbar navbar-default navbar-fixed-top" role="navigation" id="navbar">
        <div class="container">
            <div class="navbar-header">
                <button id="intro_button"  type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand scrollTo" href="{% url 'home' %}">
                    <img style="margin-top: -20%" src="{% static 'it_worker/img/logo-big.png' %}" alt="logo" width="50px" height="50px">
                </a>
            </div>

            <div class="navbar-collapse collapse" id="navigation">

                <ul class="nav navbar-nav navbar-right">
                    <li><a id="my_intro" href="{% url 'home' %}">Home</a></li>
                    <li><a id="my_intro" href="{% url 'about' %}">About</a></li>
                    <li><a id="my_intro" href="{% url 'projects' %}">Projects</a></li>
                    <li><a id="my_intro" href="{% url 'art' %}">Art</a></li>
                </ul>
            </div>
            <!--/.nav-collapse -->

        </div>
    </div>
    <!-- /#navbar -->

    <!-- *** NAVBAR END *** -->
    {% endblock %}