blog/urls.py
from django.conf.urls import url, include

from .views import *


urlpatterns = [
    url(r'^$', view=blog_homepage,name='blog_homepage'),
    url(r'^(?P<slug>[-\w]+)/$', view=blog_category,name='blog_category'),
    url(r'^create/$', view=create_post,name='blog_create'),
    url(r'^edit/(?P<slug>[-\w]+)/$', view=edit_post,name='blog_edit'),
    url(r'^detail/(?P<slug>[-\w]+)/$', view=blog_details, name='blog_detail'),




    ]

vavouras/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.conf.urls.static import static
from homepage.views import *
from django.conf import settings
from django.contrib.sitemaps.views import sitemap
from site_map.views import *
from django.views.generic import TemplateView


sitemaps = {
    'art':ArtSitemap,
    'project':ProjectSitemap,
}

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', Homepage.as_view(), name='home'),
    url(r'^about/$', AboutPage.as_view(), name='about'),
    url(r'^art/$', ArtPage.as_view(), name='art'),
    url(r'^art/(?P<slug>[-\w]+)/$', view=choosed_art, name='choosed_art'),
    url(r'^projects/$', ProjectsPage.as_view(), name='projects'),
    url(r'^project/(?P<slug>[-\w]+)/$', view=project, name='project'),
    url(r'^project/image/(?P<dk>\d+)/$', view=project_image, name='project_image'),
    url(r'^project-about/(?P<slug>[-\w]+)/$', view=project_about, name='project_about'),
    url(r'^message$', view=message_success, name='message'),
    url(r'^sitemap\.xml',sitemap, {'sitemaps': sitemaps}),
    url(r'^robots.txt$', TemplateView.as_view(template_name="it_worker/robots.txt", content_type="text/plain"), name="robots_file")

]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.conf import settings

from django.contrib.contenttypes.models import ContentType

# Create your models here.


def post_upload():
    return '/post_images'

class PostTags(models.Model):
    title = models.CharField(max_length=100, unique=True)

    def __str__(self):
        return self.title

class PostCategory(models.Model):
    title = models.CharField(max_length=100, unique=True)
    slug = models.SlugField(blank=True, null=True, allow_unicode=True)
    content = models.CharField(max_length=150, null=True, blank=True)

    def __str__(self):
        return self.title

class Post(models.Model):
    title = models.CharField(max_length=100, unique=True, verbose_name='Title')
    image = models.FileField(upload_to='post_images/', verbose_name='Image - not used atm', blank=True)
    lead_content = models.TextField(null=True, blank=True, verbose_name='Name of the Site')
    content = models.TextField(verbose_name='Short description or Intro')
    href = models.CharField(max_length=200)
    #user = models.ForeignKey(settings.AUTH_USER_MODEL, default=1)
    #publish = models.DateField(auto_now=True, auto_now_add=False)
    #updated = models.DateTimeField(auto_now=True, auto_now_add=False)
    slug = models.SlugField(unique=True,null=True, blank=True, allow_unicode=True, verbose_name='Slug - Dont bother with that ')
    #seo = models.CharField(max_length=100, blank=True)
    #meta_description = models.CharField(max_length=100, blank=True)
    #category = models.ForeignKey(PostCategory, null=True)


    def __str__(self):
        return self.title

    @property
    def get_content_type(self):
        instance = self
        content_type = ContentType.objects.get_for_model(instance.__class__)
        return content_type

blog/forms.py
from django import forms
from .models import *



class PostCreate(forms.ModelForm):
    title = forms.CharField(label="Τίτλος 'Αθρου", widget=forms.TextInput(attrs={'onkeyup':"myTitle()",}))
    lead_content = forms.CharField(label='Πρώτα Σχόλια', widget=forms.Textarea(attrs={'onkeyup':"myLeadCon()",}))
    content = forms.CharField(label='Βασικό Κείμενο', widget=forms.Textarea(attrs={'onkeyup':"myCon()",}))
    #content = forms.CharField(label='Βασικό Κείμενο', widget=FroalaEditor(attrs={'onkeyup':"myCon()",}))
    #user = forms.ChoiceField(widget=forms.HiddenInput())
    #publish = forms.DateTimeField(widget=forms.DateTimeField())

    class Meta:
        model=Post
        fields = '__all__'
        exclude=['publish','user']

class PostTagForm(forms.ModelForm):

    class Meta:
        model = PostTags
        fields= '__all__'

class PostCategoryForm(forms.ModelForm):

    class Meta:
        model = PostCategory
        fields = '__all__'

blog/views.py
from django.shortcuts import render, render_to_response,get_list_or_404, HttpResponseRedirect
from .models import *
from django.template.context_processors import csrf
from django.contrib.contenttypes.models import ContentType
# Create your views here.

'''

def blog_homepage(request):
    welcome_page = WelcomePage.objects.get(id=1)
    categories = CategorySite.objects.all().filter(category__isnull=True).order_by('id')
    posts = Post.objects.all() or get_list_or_404
    post_category = PostCategory.objects.all()
    return render_to_response('obaju/blog.html',{'posts':posts,
                                                 'categories':categories,
                                                 'welcome_page':welcome_page,
                                                 'post_cat':post_category
                                                 })
def blog_category(request,slug):
    welcome_page = WelcomePage.objects.get(id=1)
    categories = CategorySite.objects.all().filter(category__isnull=True).order_by('id')
    choosed_category = PostCategory.objects.get(slug=slug)
    posts = Post.objects.filter(category = choosed_category) or get_list_or_404
    post_category = PostCategory.objects.all()
    return render_to_response('obaju/blog.html',{'posts':posts,
                                                 'categories':categories,
                                                 'welcome_page':welcome_page,
                                                 'post_cat':post_category,
                                                 'choosed_category':choosed_category,
                                                 })

def blog_details(request,slug):
    welcome_page = WelcomePage.objects.get(id=1)
    categories = CategorySite.objects.all().filter(category__isnull=True).order_by('id')
    post_category = PostCategory.objects.all()
    post= Post.objects.get(slug=slug)
    content_type = post.get_content_type
    object_id = post.id
    comments = Comment.my_query.filter_by_instance(instance=post)

    if request.POST:
        form_comment = CommentForm(request.POST)
        if form_comment.is_valid():
            get_data = form_comment.cleaned_data.get('content')
            new_comment = Comment.objects.create(content_type=content_type,
                                                object_id =object_id,
                                                user=request.user,
                                                comment_type=CommentType.objects.get(id = 1),
                                                content = get_data,
                                                )
            new_comment.save()
            return HttpResponseRedirect(request.META.get('HTTP_REFERER'))
    else:
        form_comment = CommentForm()

    context={
        'post':post,
        'blog_detail':True,
        'categories':categories,
        'welcome_page':welcome_page,
        'post_cat':post_category,
        'comments':comments,
        'form_comment':form_comment,

    }
    context.update(csrf(request))

    return render(request,'obaju/post.html',context)



def create_post(request):
    posts  = Post.objects.all() or get_list_or_404
    if request.POST:
        form = PostCreate(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect('/blog/')
    else:
        form = PostCreate()
    context={
            'posts':posts,
            'create':True,
            'form':form,

            }
    return render(request,'blog/blog_homepage.html',context)





def edit_post(request,slug):
    posts  = Post.objects.all() or get_list_or_404
    post= Post.objects.get(slug=slug)
    if request.POST:
        form = PostCreate(request.POST,instance=post)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect('/blog/')
    else:
        form = PostCreate(instance=post)
    context ={'posts':posts,
            'create':True,
            'form':form,}
    context.update(csrf(request))
    return render(request, 'blog/blog_homepage.html',context)
'''

blog/templates/blog/blog_homepage.html
{% extends 'inventory/welcome_page.html' %}

{% block my_static %}
    {% load staticfiles %}
    {{ form.media }}
    <script  src="{% static 'marked-master/marked.min.js' %}"></script>
    <script type="text/javascript">


        $(document).ready(function(){
            $(".contentmark").each(function(){
            var content = $(this).text()
            var markedContent = marked(content)
            $(this).html(markedContent)
            })
            $(".contentmark img").each(function(){
                $(this).addClass("ui medium image");
            })
            var getTitle = $("#id_title");
            console.log('hello')
            $('#my_title').text(getTitle.val())
            console.log(getTitle.val())
            $( "#id_title" ).keyup(function() {
                console.log(getTitle);
            });
        })


</script>
{% endblock %}
{% block center %}
    <div class="contentmark">
    {{ post.content }}
    </div>
    {% if blog_detail %}
        <div class="ui card">
            <div class="content">
                <i class="right floated like icon"></i>
                <i class="right floated star icon"></i>
                <div class="header">{{ post.title }}</div>
                <div class="description">
                    <div class="contentmark">
                        {{ post.content }}
                    </div>

                </div>
            </div>
            <div class="extra content">
            <span class="left floated like">
              <i class="like icon"></i>
              Like
            </span>
            <span class="right floated star">
              <i class="star icon"></i>
              Favorite
            </span>
          </div>
        </div>
        <a href="{% url 'blog_edit' post.slug %}" class="ui edit button">edit </a>
        <div class="ui comments">
                          <h3 class="ui dividing header">Comments</h3>
                          {% for comment in comments %}
                              <div class="comment">
                                  <div class="content">
                                      <a class="author">{{ comment.user.username }}</a>
                                      <div class="metadata">
                                          <span class="date">{{ comment.timestamp|timesince }} ago</span>
                                      </div>
                                      <div class="text">
                                          {{ comment.content }}
                                      </div>
                                      <div class="actions">
                                <a class="reply">Reply</a>
                              </div>
                                  </div>
                              </div>
                          {% endfor %}

                    </div>

    {% else %}
    <div class="row">
        <div class="ui header">
            Όλα τα Posts
        </div>
        <div class="ui segments">
            {% for post in posts %}
                <div class="ui segment">
                    <a href="{% url 'blog_detail' post.slug %}" class="ui header">{{ post.title }}</a>
                    <div class="ui comments">
                          <h3 class="ui dividing header">Comments</h3>
                          {% for comment in comments %}
                              <div class="comment">
                                  <div class="content">
                                      <a class="author">{{ comment.user.username }}</a>
                                      <div class="metadata">
                                          <span class="date">{{ comment.timestamp|timesince }} ago</span>
                                      </div>
                                      <div class="text">
                                          {{ comment.content }}
                                      </div>
                                      <div class="actions">
                                <a class="reply">Reply</a>
                              </div>
                                  </div>
                              </div>
                          {% endfor %}

                    </div>
                </div>
                <div class="ui dividing segment"></div>
            {% endfor %}
        </div>
    </div>
    {% endif %}

{% endblock %}


{% block left_side %}
    <div class="row ">
    {% if create %}
        <form method="post" enctype="multipart/form-data" class="ui small form">{% csrf_token %}
         {{ form }}
        <input type="submit" class="ui green button">
        </form>
    {% else %}
        <a href="{% url 'blog_create' %}" class="ui green button">Δημιουργία</a>
    {% endif %}
    </div>

{% endblock %}


{% block right_side %}
    <div class="row ">
    {% if create %}
        <div class="ui card">
            <div class="content">
                <i class="right floated like icon"></i>
                <i class="right floated star icon"></i>
                <div id='my_title' class="header">{{ post.title }}</div>
                <div class="description">
                    <div class="contentmark">
                        {{ post.content }}
                    </div>

                </div>
            </div>
            <div class="extra content">
            <span class="left floated like">
              <i class="like icon"></i>
              Like
            </span>
            <span class="right floated star">
              <i class="star icon"></i>
              Favorite
            </span>
          </div>
        </div>
    {% else %}
        <a href="{% url 'blog_create' %}" class="ui green button">Δημιουργία</a>
    {% endif %}
    </div>

{% endblock %}